version: "3.7"

services:
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discord
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
